services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules  # ✅ no ./frontend:/app!
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    restart: always
